language: android

android:
  components:
    - tools
    - platform-tools
    - build-tools-24.0.0
    - extra-android-m2repository
    - android-24

jdk:
  - oraclejdk8

script:
  - ./gradlew clean check

after_success:
  - .buildscript/deploy_snapshot.sh

branches:
  except:
    - gh-pages

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.gradle
