version: 2
jobs:
  build:
    docker:
      - image: circleci/android:api-26
    steps:
      - run:
          name: Accept licenses
          command: yes | sdkmanager --licenses || exit 0
      - run:
          name: Update licenses
          command: yes | sdkmanager --update || exit 0
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - run:
          name: Unit Test
          command: ./gradlew test
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
